
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tasky.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Task
{

    public int TaskId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double Hours { get; set; }

    public int ProjectId { get; set; }

    public System.Guid UserId { get; set; }

    public int ProjectTaskId { get; set; }

    public System.DateTime Date { get; set; }



    public virtual Project Project { get; set; }

    public virtual ProjectTask ProjectTask { get; set; }

    public virtual User User { get; set; }

}

}
